apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohdsi-webapi-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: ohdsi-webapi
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ohdsi-webapi
        public: "yes"
        GEN3_DATE_LABEL
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ohdsi-webapi
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: ohdsi-webapi-settings
          secret:
            secretName: "ohdsi-webapi-settings"
      containers:
        - name: ohdsi-webapi
          GEN3_OHDSI_WEBAPI_IMAGE|-image: quay.io/cdis/ohdsi-webapi:latest-|
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: "ohdsi-webapi-settings"
              readOnly: true
              mountPath: "/var/lib/ohdsi/webapi/META-INF/maven/org.ohdsi/WebAPI/WebAPIConfig/settings.xml"
              subPath: "settings.xml"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              cpu: 1
              memory: 2400Mi  
