apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohdsi-broadsea-webtools-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: ohdsi-broadsea-webtools
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ohdsi-broadsea-webtools
        public: "yes"
        GEN3_DATE_LABEL
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ohdsi-broadsea-webtools
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: broadsea-config-local
          configMap:
            name: broadsea-config-local
      containers:
        - name: ohdsi-broadsea-webtools
          GEN3_OHDSI_BROADSEA_WEBTOOLS_IMAGE|-image: ohdsi/broadsea-webtools:latest-|
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          ports:
          - containerPort: 8080
          envFrom:
            - secretRef:
                name: ohdsi-broadsea-webtools-config
          volumeMounts:
            - name: broadsea-config-local
              readOnly: true
              mountPath: /usr/local/tomcat/webapps/atlas/js/config-local.js
              subPath: config-local.js
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              cpu: 1
              memory: 2400Mi  
